# Generated by Django 4.0.5 on 2023-06-12 17:39

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('distance', models.IntegerField()),
                ('averageSpeed', models.FloatField()),
                ('duration', models.DurationField()),
                ('time', models.DateTimeField()),
                ('maxSpeed', models.FloatField()),
                ('accumulatedDrop', models.IntegerField()),
                ('routeCoordinates', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backend.activity')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
            ],
            bases=('backend.activity',),
        ),
    ]
